name: Deploy to Github Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          pnpm run build
          pnpm run export

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEA6LtzA3dvA3MUx2oRtjxINRiyB9bF4B8RyznfVlb9LQ4QQblW9H3zW8UPfyIFKL9iQVhmmPjQC5vVSef/ELvLaZRWMonz5uuYmURGxq0VM8FAuJqaLXjshB8REG0Ye55Vz2rrtaYkVnH331K6MBWAencICnj4YIr4f2wH5SM+t+N7k6dK/FmMj6B2jVwPssWcDPyFkNe5OUtmzX+N7gmI63LCy+ltbtxqKpFg8Nb8b1CsuRii73GzcDE+zIcvWZPxTmtrOWZwFbPI7Ju+Zs/7PGYYuBCnm08vnyN5yFBUSO2Y9JqbEkFw9X5dZY7aEg49DW2GQPwOJqFNHeL184nWuTcStfZQG5N/jFiEVIQiUMTCIX6zhvJXZB9ft6m9is6paGt/zLDtYcl8VoagOJYT3vjMcPSqoAAcFx4EKg0LA7K8b3OsKMmGs7jmBcLMuDkAAQNmWFkCzT10LvEJ950AyWHYu3YQL5rl39/U0uEGwIGJh9ThtiEqZauBZztg2J6m5j0uesK9v5Eht+w443YWlVCFb5YVO25TgE9fIJbQ07Gn7EMP/rj/8j1Pg1kWMNJ+dS6WvUFusxUSMVt7R5wy6Thm+zrxcpHbF76/xk8sTjwknWHPC/Nlkoh4hiR2eUtd7n/4Fka+c/gBb0POo86M81sFErLk1U6Ve/dekilBr9cAAAdoY4RoL2OEaC8AAAAHc3NoLXJzYQAAAgEA6LtzA3dvA3MUx2oRtjxINRiyB9bF4B8RyznfVlb9LQ4QQblW9H3zW8UPfyIFKL9iQVhmmPjQC5vVSef/ELvLaZRWMonz5uuYmURGxq0VM8FAuJqaLXjshB8REG0Ye55Vz2rrtaYkVnH331K6MBWAencICnj4YIr4f2wH5SM+t+N7k6dK/FmMj6B2jVwPssWcDPyFkNe5OUtmzX+N7gmI63LCy+ltbtxqKpFg8Nb8b1CsuRii73GzcDE+zIcvWZPxTmtrOWZwFbPI7Ju+Zs/7PGYYuBCnm08vnyN5yFBUSO2Y9JqbEkFw9X5dZY7aEg49DW2GQPwOJqFNHeL184nWuTcStfZQG5N/jFiEVIQiUMTCIX6zhvJXZB9ft6m9is6paGt/zLDtYcl8VoagOJYT3vjMcPSqoAAcFx4EKg0LA7K8b3OsKMmGs7jmBcLMuDkAAQNmWFkCzT10LvEJ950AyWHYu3YQL5rl39/U0uEGwIGJh9ThtiEqZauBZztg2J6m5j0uesK9v5Eht+w443YWlVCFb5YVO25TgE9fIJbQ07Gn7EMP/rj/8j1Pg1kWMNJ+dS6WvUFusxUSMVt7R5wy6Thm+zrxcpHbF76/xk8sTjwknWHPC/Nlkoh4hiR2eUtd7n/4Fka+c/gBb0POo86M81sFErLk1U6Ve/dekilBr9cAAAADAQABAAACAQCJtsHr/zRVmjdleMJaT3l60c4nDVOxtzDUTL53XKobiwLboUxvCEiEuSreU8cxwW3mtOShCDozZFblkL5BrJ5FL12CMld9AVQe/WPUFH9DTMt7cSBiX/e0hp2WVrfyDlNAlUg9CL7f2DiQkWdTJKYN0XmUmNiAaDt7SvWxBRYLwjRRvuCESoj+RDlilGNFqeEZXiO6/avA13lRiHT3sfSvPg0+lDYJL6wy3Cu817owNFDAhm+DuIgxjzJV3HiMTRqxCKc+I/uXG/d86vvT4qYLq25dHJ3RLR5E0L0zZzU4oj+sHgA84TRyT//8JHetz3cZBwI2WfAVs8TqNm7LWXkQpy7jAuEgVhMyntylEiF4m9Fv4o6tiJd/Fc321EE/hZ5kC3r67padf70GO71aYnzd0aHNjzacGkag0b+97+BYUZVWks0pL7y2cS0nPi3qi01wKt2mNYZAKy/ziASzKHajfuUUOPUs4RFZi4EOe/83wQ3q8CHe29szN81NhKlz2xACmxSPoWq6VOvMilTy8mMsxGiF4wXQg99VIgFUl0gW9LIbi/hKwJYc55aYs17qnebcoudWra9YMVe5Sj9TntdelUbkKdS1w4ABFmuEiDS5wJwTcLIn+ZvmT0rNK31a7wQHuQUm6rz8gFNo6A+aSDpIseeYYYvQiQvYmk8EarSlYQAAAQA7ll6Q7pIRGheRQmlOXT5gDov9e5gbiReCr8n7L7/3MzMduUGA/k++SPyESSDLOrC8ufj0KKp4AUuJO34KDjALWntqIeTx9ObCcIx79mvRAXiioQrOzv3qL1riU1xPSTpRFTb9S3VrP8g77B7N9u5z0ywZI8wgHAyUgy4XndWU86E0ZHIh8bFRipL1nva1VvcwRtlqKCDcLB9m580FbCmUPUatcXDXvVpjGZKcUoaVVDxy6skNOcAJDQL2gZpQctN/H2vv86qtfCzf60CwegNth+GoFAmhzFbV9xwJtsmA6Bk5rlpIwwnCjouFdo/YpJI+GnRNCobo/BWBS2cseZfQAAABAQD5zqExprdUQ/oVPQTaDqFY650y12YmiJy3Tv868TRUSelHszvMdTq0NjGMzNY46bICVDVKCDwfF8em1IMEle4A/ey7wscqCLyDIehaV2sIKkuTf3XBzPbbYlcpSLXwEoqwWGEytTPka6ImHqA5mYCFgLfop0Lqg1Xqz6AGUyMKGA8YP3z+GpL6YBA0uQpe4DSF39/ByfRA/wN72c92SD1otZWDNriGH2flMbOeq3dYkX4OrBjC1svQw5BqOyuwvZnv7E/Wdxi85UqIOkbeA953bgSUim2EgR3M1mxEdlBOpQndlFIHrfHiiO6FfPWLzOUeXLU0deTQRtPswavhj4yrAAABAQDugHSpLDw/hrdmzHKNzm6qshRPq/bRALau7i2UKUlBpEWJkmEJHBpd2H8Q4V10Ha8SaLZJTZSk0iwvfeuH9CwnDWHlRx7Wgh+SREijVaMACa2Q+c+IDPNkoVaNegv1lhqj0dGnm3q79IHRuTHoX2pIuyCu6OP6uagyjQohwg30peGbVzjFYzjX4mogG41PyPx6+SVkap/PCZhpORFGXjERaL0pf2YXMtYJgs9fNx2FUrA9s7V+KFQNaTOVsu8ELioMG1YteER+tWUiKLCcUopMB1gahQRixe6Sl4kvVQLNdqZ+3mS9JpaKE8+lalqwWuq/NDFjrvVs7hTDt40LgtGFAAAALDQ4ODE3NjA2K21hbnRhaWxzMDlAdXNlcnMubm9yZXBseS5naXRodWIuY29tAQIDBAUG }}
          publish_dir: ./out
